// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDzWLpbFLE1z9tJFuWk78qzYhLMFW5WHo',
    appId: '1:3402597773:web:bc5d5cbb7f950770d169c4',
    messagingSenderId: '3402597773',
    projectId: 'travelmanager-16ade',
    authDomain: 'travelmanager-16ade.firebaseapp.com',
    storageBucket: 'travelmanager-16ade.appspot.com',
    measurementId: 'G-SWJ1KJ04EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlazupY4Kch6L6Ol7X07_C3D9jTWDl5QI',
    appId: '1:3402597773:android:28c3776ebf210630d169c4',
    messagingSenderId: '3402597773',
    projectId: 'travelmanager-16ade',
    storageBucket: 'travelmanager-16ade.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp0J0mC2DwpRi2OqAzcRTIaQCZjzo98Wg',
    appId: '1:3402597773:ios:7562f37e4a819e05d169c4',
    messagingSenderId: '3402597773',
    projectId: 'travelmanager-16ade',
    storageBucket: 'travelmanager-16ade.appspot.com',
    iosBundleId: 'com.example.travelManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp0J0mC2DwpRi2OqAzcRTIaQCZjzo98Wg',
    appId: '1:3402597773:ios:7562f37e4a819e05d169c4',
    messagingSenderId: '3402597773',
    projectId: 'travelmanager-16ade',
    storageBucket: 'travelmanager-16ade.appspot.com',
    iosBundleId: 'com.example.travelManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDzWLpbFLE1z9tJFuWk78qzYhLMFW5WHo',
    appId: '1:3402597773:web:f27549875e61bf16d169c4',
    messagingSenderId: '3402597773',
    projectId: 'travelmanager-16ade',
    authDomain: 'travelmanager-16ade.firebaseapp.com',
    storageBucket: 'travelmanager-16ade.appspot.com',
    measurementId: 'G-GZNQYPZ3ZH',
  );
}
